kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: lb2
  namespace: testproject2
  selfLink: /apis/route.openshift.io/v1/namespaces/testproject2/routes/lb2
  uid: 8d445789-04da-4223-aa6b-24a160db0c67
  resourceVersion: '300862587'
  creationTimestamp: '2020-06-10T22:00:55Z'
  labels:
    app: prod
    name: prod
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: lb2-testproject2.apps.ca-central-1.starter.openshift-online.com
  to:
    kind: Service
    name: prod
    weight: 100
  alternateBackends:
    - kind: Service
      name: prodfeat
      weight: 0
  port:
    targetPort: 7800-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
status:
  ingress:
    - host: lb2-testproject2.apps.ca-central-1.starter.openshift-online.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-06-10T22:00:56Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps.ca-central-1.starter.openshift-online.com
